Prepare code signign only once

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,6 +50,7 @@ before_install:
   - |
     echo "[INFO]: TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
     echo "[INFO]: TRAVIS_PULL_REQUEST_SLUG: ${TRAVIS_PULL_REQUEST_SLUG}"
+    PREPARE_SIGNING=false
     if [ ! -z "${TRAVIS_PULL_REQUEST_SLUG}" ]
     then
       if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]
@@ -57,21 +58,8 @@ before_install:
         echo "[INFO]: pull request."
         if [ "${TRAVIS_PULL_REQUEST_SLUG}" == "${TRAVIS_REPO_SLUG}" ]
         then
+          PREPARE_SIGNING=true
           echo "[INFO]: Inside repo '${TRAVIS_REPO_SLUG}'. Prepare code signing."
-          openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in cfg/codesigning.asc.enc -out cfg/codesigning.asc -d
-          if [ "$?" == "0" ]
-          then
-            echo "[INFO]: decrypting private key succeeded. Importing ..."
-            gpg --verbose --fast-import cfg/codesigning.asc
-            if [ "$?" == "0" ]
-            then
-              echo "[INFO]: private key imported."
-            else
-              echo "[ERROR]: private key import failed."
-            fi
-          else
-            echo "[ERROR]: decrypting private key failed."
-          fi
         else
           echo "[INFO]: Pull request proposed from outside base repo. Not preparing code signing."
         fi
@@ -81,23 +69,28 @@ before_install:
     else
       echo "[INFO]: No pull request."
       if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]; then
+        PREPARE_SIGNING=true
         echo "[INFO]: Inside repo '${TRAVIS_REPO_SLUG}'. Prepare code signing."
-        openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in cfg/codesigning.asc.enc -out cfg/codesigning.asc -d
-        if [ "$?" == "0" ]
-        then
-          echo "[INFO]: decrypting private key succeeded. Importing ..."
-          gpg --verbose --fast-import cfg/codesigning.asc
-          if [ "$?" == "0" ]
-          then
-            echo "[INFO]: private key imported."
-          else
-            echo "[ERROR]: private key import failed."
-          fi
-        else
-          echo "[ERROR]: decrypting private key failed."
-        fi
       else
         echo "[INFO]: No pull request and outside base repo. Not preparing code signing."
+      fi
+    fi
+    if [ "${PREPARE_SIGNING}" = "true" ]
+    then
+      echo "[INFO]: Prepare code signing"
+      openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in cfg/codesigning.asc.enc -out cfg/codesigning.asc -d
+      if [ "$?" == "0" ]
+      then
+        echo "[INFO]: decrypting private key succeeded. Importing ..."
+        gpg --verbose --fast-import cfg/codesigning.asc
+        if [ "$?" == "0" ]
+        then
+          echo "[INFO]: private key imported."
+        else
+          echo "[ERROR]: private key import failed."
+        fi
+      else
+        echo "[ERROR]: decrypting private key failed."
       fi
     fi
 deploy:
