More logging and fixes in the control flow

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,8 +9,8 @@ jdk:
 install:
   - |
     PROFILE=noop
-    echo "TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
-    echo "TRAVIS_PULL_REQUEST_SLUG: ${TRAVIS_PULL_REQUEST_SLUG}"
+    echo "[INFO]: TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
+    echo "[INFO]: TRAVIS_PULL_REQUEST_SLUG: ${TRAVIS_PULL_REQUEST_SLUG}"
     if [ ! -z "${TRAVIS_PULL_REQUEST_SLUG}" ]
     then
       if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]
@@ -28,9 +28,10 @@ install:
     else
       echo "[INFO]: No pull request."
       if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]
+      then
         echo "[INFO]: Configuring code signing."
         PROFILE=signing
-      then
+      else
         echo "[INFO]: No pull request and outside base repo. Not preparing code signing."
       fi
     fi
@@ -47,8 +48,8 @@ cache:
   - $HOME/.m2
 before_install:
   - |
-    echo "TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
-    echo "TRAVIS_PULL_REQUEST_SLUG: ${TRAVIS_PULL_REQUEST_SLUG}"
+    echo "[INFO]: TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
+    echo "[INFO]: TRAVIS_PULL_REQUEST_SLUG: ${TRAVIS_PULL_REQUEST_SLUG}"
     if [ ! -z "${TRAVIS_PULL_REQUEST_SLUG}" ]
     then
       if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]
@@ -57,7 +58,19 @@ before_install:
         then
           echo "[INFO]: Prepare code signing."
           openssl aes-256-cbc -K $encrypted_d5d7c7a681ca_key -iv $encrypted_d5d7c7a681ca_iv -in cfg/codesigning.asc.enc -out cfg/codesigning.asc -d
-          gpg --fast-import cfg/codesigning.asc
+          if [ "$?" == "0" ]
+          then
+            echo "[INFO]: decrypting private key succeeded. Importing ..."
+            gpg --verbose --fast-import cfg/codesigning.asc
+            if [ "$?" == "0" ]
+            then
+              echo "[INFO]: private key imported."
+            else
+              echo "[ERROR]: private key import failed."
+            fi
+          else
+            echo "[ERROR]: decrypting private key failed."
+          fi
         else
           echo "[INFO]: Pull request proposed from outside base repo. Not preparing code signing."
         fi
@@ -66,11 +79,24 @@ before_install:
       fi
     else
       echo "[INFO]: No pull request."
-      if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]
+      echo "[INFO]: TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}"
+      if [ "${TRAVIS_REPO_SLUG}" == "SAP/devops-cm-client" ]; then
         echo "[INFO]: Prepare code signing."
         openssl aes-256-cbc -K $encrypted_d5d7c7a681ca_key -iv $encrypted_d5d7c7a681ca_iv -in cfg/codesigning.asc.enc -out cfg/codesigning.asc -d
-        gpg --fast-import cfg/codesigning.asc
-      then
+        if [ "$?" == "0" ]
+        then
+          echo "[INFO]: decrypting private key succeeded. Importing ..."
+          gpg --verbose --fast-import cfg/codesigning.asc
+          if [ "$?" == "0" ]
+          then
+            echo "[INFO]: private key imported."
+          else
+            echo "[ERROR]: private key import failed."
+          fi
+        else
+          echo "[ERROR]: decrypting private key failed."
+        fi
+      else
         echo "[INFO]: No pull request and outside base repo. Not preparing code signing."
       fi
     fi
